local_backend: true
backend:
  name: github
  repo: Ryloxx/ryloxx.github.io
  branch: master
  site_domain: gifted-jones-bd395f.netlify.app
  squash_merges: true

media_folder: images/uploads
site_url: https://ryloxx.github.io
display_url: https://ryloxx.github.io
media_library:
  name: cloudinary
  config:
    cloud_name: c66bhz8dnq7
    api_key: 465797591824591
publish_mode: editorial_workflow
collections:
  - label: 'Projects'
    name: 'project'
    folder: 'data/projects'
    create: true
    extension: json
    format: json
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Body, name: body, widget: markdown }
      - { label: Link, name: link, widget: string }
      - {
          label: Code Link,
          name: code,
          widget: string,
          default: '',
          required: false,
        }
      - {
          label: Updated At,
          name: updated_at,
          widget: datetime,
          date_format: DD.MM.YYYY,
          time-format: false,
          picker_utc: true,
        }
    summary: '{{title}} {{commit_author}} {{commit_date}}'
    sortable_fields: ['commit_date', 'title', 'commit_author']
    editor:
      preview: false
    preview_path_date_field: 'updated_at'
  - label: 'Persons'
    name: 'person'
    folder: 'data/persons'
    create: true
    extension: json
    format: json
    identifier_field: name
    fields:
      - label: Name
        name: name
        widget: string
      - label: Profile picture
        name: image
        widget: image
        required: false
        media_library:
          config:
            default_transformations:
              - - fetch_format: auto
                  width: 128
                  height: 128
                  quality: auto
                  crop: fill
      - label: Bio
        name: bio
        widget: markdown
      - label: Links
        name: links
        widget: object
        fields:
          - label: GitHub
            name: github
            widget: string
            required: false
      - label: Updated At
        name: updated_at
        widget: datetime
        date_format: DD.MM.YYYY
        time-format: false
        picker_utc: true

    summary: '{{name}}'
    editor:
      preview: false
    preview_path_date_field: 'updated_at'
