name: CI
on:
  push:
    branches:
      - master
      - decap
jobs:
  dispatch:
    name: DISPATCH DEPLOY
    runs-on: ubuntu-latest
    steps:
      - name: Dispatching 'deploy-gh-pages' repository event
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: deploy-gh-pages
