name: CI
on:
  push:
    branches:
      - master
      - decap
jobs:
  dispatch:
    name: DISPATCH DEPLOY
    runs-on: ubuntu-latest
    steps:
      - name: Dispatching 'deploy' repository event
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: deploy-gh-pages
