name: Build and Deploy
on:
  workflow_dispatch:
  repository_dispatch:
    types: [deploy-gh-pages]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: master
      - name: Checkout decap
        uses: actions/checkout@v4
        with:
          ref: decap
          path: decap
      - name: Move decap into root
        run: "mv decap/* . && rm -rf decap"
      - name: Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Build
        run: npm run build
      - name: Deploy "build"
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
