name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Build
        run: npm run listing
      - name: Copy to "build"
        run: rsync -a --exclude={'*.github','.git','package.json','listing.js'} . build/
      - name: Deploy "build"
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
